version: '3.1'

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: booksdb
      POSTGRES_PASSWORD: example
  php:
    image: snaksa/scanner
    restart: always
    build:
      context: .
    links:
      - db
    volumes:
      - .:/var/www/html
    ports:
      - "8080:80"
